apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
  namespace: other
data:
  my.cnf: |-
    [mysql]
    default-character-set=utf8mb4

    [client]
    default-character-set=utf8mb4

    [mysqld]
    character-set-client-handshake=false
    character-set-server=utf8mb4
    init_connect='SET NAMES utf8mb4'
    sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION