apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-conf
  namespace: other
data:
  init.sh: |-
    #!/bash/bin
    mongo <<EOF
    use admin;
    db.auth( "root", "123456" );
    use test;
    db.createUser({
      user: "test",
      pwd: "123456",
      roles: ["readWrite"]
    });
    EOF
